### ISSUE TITLE
Authme BUG big/small characters. Fix fast, help fast.. Thanks.

### ISSUE THREAD

**Issue by NickFirenzo** [Multiplayer-italia/AuthMe-Reloaded#7]
Hi, 
I need help please help me
How to prevent join with big/small characters?
TOPIC: https://www.spigotmc.org/threads/help-me-fast-please-small-and-large-characters-the-name-when-do-join.79653/

**Comment by Xephi** [comment]
Wrong repo :/ Can you re-open this here :
https://github.com/Xephi/AuthMeReloaded

**Comment by NickFirenzo** [comment]
Already solved
